Repository vitessio/website, pull requests merged in 2021-12, with the labels that each got.

#889 documenting ddl_strategy flags and migration_context
  content/en/docs/user-guides/schema-changes/audit-and-control.md
  content/en/docs/user-guides/schema-changes/ddl-strategies.md
  content/en/docs/user-guides/schema-changes/ddl-strategy-flags.md
  content/en/docs/user-guides/schema-changes/declarative-migrations.md
  content/en/docs/user-guides/schema-changes/managed-online-schema-changes.md
  content/en/docs/user-guides/schema-changes/postponed-migrations.md
  content/en/docs/user-guides/schema-changes/recoverable-migrations.md
  content/en/docs/user-guides/schema-changes/revertible-migrations.md
  content/en/docs/user-guides/schema-changes/table-lifecycle.md
Labels: documentation

#896 Adding additional noted edits
  content/en/docs/get-started/local-brew.md
  content/en/docs/get-started/local-docker.md
  content/en/docs/get-started/local-mac.md
  content/en/docs/get-started/local.md
  content/en/docs/reference/features/connection-pools.md
Labels: documentation

#900 [Blog] Connecteam - our Vitess story
  content/en/blog/2021-12-06-connecteam-story.md
Labels: blog

#898 addition to the ACL user guide
  content/en/docs/user-guides/configuration-advanced/authorization.md
Labels: documentation

#891 Document concurrent migrations
  content/en/docs/design-docs/online-ddl/scheduler.md
  content/en/docs/user-guides/schema-changes/_index.md
  content/en/docs/user-guides/schema-changes/concurrent-migrations.md
  content/en/docs/user-guides/schema-changes/ddl-strategy-flags.md
Labels: documentation

#909 Blog- rails that scales - powered by vitess
  content/en/blog/2021-12-16-rails-that-scales.md
Labels: do-not-merge, blog

#915 removing outdated wording
  content/en/docs/concepts/tablet.md
Labels: documentation
