Repository vitessio/website, pull requests merged in 2021-11, with the labels that each got.

#853 Why write a new planner [Blog]
  content/en/blog/2021-11-02-why-write-new-planner.md
Labels: blog

#871 Clarify 'online' strategy supports ETA and progress
  content/en/docs/user-guides/schema-changes/ddl-strategies.md
Labels: documentation

#879 Default collation documentation
  content/en/docs/reference/programs/vtgate.md
  content/en/docs/reference/programs/vttablet.md
  content/en/docs/user-guides/vschema-guide/collations.md
Labels: documentation

#892 Add KubeCon NA 2021 Maintainer talk
  content/en/docs/resources/presentations.md
Labels: documentation

#895 Adds planner_version documentation for the vttestserver image
  content/en/docs/get-started/vttestserver-docker-image.md
Labels: enhancement, documentation
