Repository vitessio/website, pull requests merged in 2022-02, with the labels that each got.

#955 Add docs for the durability policies
  content/en/docs/13.0/user-guides/configuration-advanced/reparenting.md
  content/en/docs/13.0/user-guides/configuration-basic/durability_policy.md
  content/en/docs/13.0/user-guides/configuration-basic/vtctld.md
  content/en/docs/13.0/user-guides/configuration-basic/vtorc.md
Labels: documentation

#950 Document new log message sanitization vttablet flag
  content/en/docs/14.0/design-docs/vttablet/tablet-params.md
  content/en/docs/14.0/reference/programs/vttablet.md
Labels: documentation, do-not-merge

#969 Documents https://github.com/vitessio/vitess/pull/9636
  content/en/docs/13.0/design-docs/vttablet/tablet-params.md
  content/en/docs/13.0/reference/programs/vttablet.md
Labels: do-not-merge

#974 `Announcing Vitess 13` blog post
  content/en/blog/2022-02-22-announcing-vitess-13.md
Labels: blog

#979 Addition of `enable_set_var` to vtgate program reference
  content/en/docs/14.0/reference/programs/vtgate.md
  content/en/docs/14.0/reference/query-serving/reserved-conn.md
Labels: documentation
