Repository vitessio/website, pull requests merged in 2022-01, with the labels that each got.

#932 Add a guide explaining how to create a sample PR
  content/en/docs/13.0/contributing/reference/sample-first-issue.md
Labels: documentation

#930 Update docs for ISP and PRS
  content/en/docs/13.0/user-guides/configuration-advanced/reparenting.md
  content/en/docs/13.0/user-guides/configuration-basic/init-shard-primary.md
  content/en/docs/13.0/user-guides/configuration-basic/initialize-shard-primary.md
Labels: documentation

#938 Fixes for v13 links
  content/en/docs/11.0/user-guides/schema-changes/_index.md
  content/en/docs/13.0/concepts/vschema.md
  content/en/docs/13.0/reference/compatibility/mysql-compatibility.md
  content/en/docs/13.0/reference/features/mysql-replication.md
  content/en/docs/13.0/reference/programs/vtctl/_index.md
  content/en/docs/13.0/resources/presentations.md
  content/en/docs/13.0/user-guides/configuration-advanced/comment-directives.md
  content/en/docs/13.0/user-guides/configuration-advanced/integration-with-orchestrator.md
  content/en/docs/13.0/user-guides/configuration-advanced/region-sharding.md
  content/en/docs/13.0/user-guides/configuration-advanced/reparenting.md
  content/en/docs/13.0/user-guides/configuration-advanced/resharding.md
  content/en/docs/13.0/user-guides/configuration-basic/exporting-data.md
  content/en/docs/13.0/user-guides/migration/move-tables.md
  content/en/docs/13.0/user-guides/schema-changes/_index.md
  content/en/docs/13.0/user-guides/schema-changes/audit-and-control.md
  content/en/docs/13.0/user-guides/sql/vtexplain-in-bulk.md
  content/en/docs/13.0/user-guides/sql/vtexplain.md
Labels: documentation

#910 Addition of the schema tracking blog post
  content/en/blog/2022-01-11-schema-tracking.md
Labels: do-not-merge, blog

#939 Round two of link fixes after the versioning
  content/en/docs/11.0/concepts/vstream.md
  content/en/docs/11.0/design-docs/vreplication/life-of-a-stream.md
  content/en/docs/11.0/reference/programs/vtctl/_index.md
  content/en/docs/11.0/reference/vreplication/progress.md
  content/en/docs/11.0/user-guides/configuration-advanced/authorization.md
  content/en/docs/11.0/user-guides/configuration-advanced/region-sharding.md
  content/en/docs/11.0/user-guides/configuration-advanced/resharding.md
  content/en/docs/11.0/user-guides/configuration-basic/exporting-data.md
  content/en/docs/11.0/user-guides/sql/vtexplain-in-bulk.md
  content/en/docs/11.0/user-guides/sql/vtexplain.md
  content/en/docs/12.0/concepts/vschema.md
  content/en/docs/12.0/concepts/vstream.md
  content/en/docs/12.0/design-docs/vreplication/life-of-a-stream.md
  content/en/docs/12.0/reference/features/mysql-replication.md
  content/en/docs/12.0/reference/vreplication/progress.md
  content/en/docs/12.0/user-guides/configuration-advanced/authorization.md
  content/en/docs/12.0/user-guides/configuration-advanced/region-sharding.md
  content/en/docs/12.0/user-guides/configuration-advanced/resharding.md
  content/en/docs/12.0/user-guides/configuration-basic/exporting-data.md
  content/en/docs/12.0/user-guides/migration/cutover.md
  content/en/docs/12.0/user-guides/migration/move-tables.md
  content/en/docs/12.0/user-guides/sql/vtexplain-in-bulk.md
  content/en/docs/12.0/user-guides/sql/vtexplain.md
  content/en/docs/13.0/concepts/vstream.md
  content/en/docs/13.0/design-docs/vreplication/life-of-a-stream.md
  content/en/docs/13.0/user-guides/migration/cutover.md
  content/en/docs/13.0/user-guides/schema-changes/_index.md
  content/en/docs/13.0/user-guides/sql/vtexplain.md
  content/zh/docs/11.0/get-started/_index.md
  content/zh/docs/12.0/get-started/_index.md
  content/zh/docs/13.0/get-started/_index.md
  static/img/VReplicationFlow.png
  static/img/VStream.svg
Labels: documentation

#941 last round of link fixes
  content/en/docs/11.0/reference/compatibility/mysql-compatibility.md
  content/en/docs/11.0/reference/programs/vtctl/keyspaces.md
  content/en/docs/11.0/reference/vreplication/v1/_index.md
  content/en/docs/11.0/reference/vreplication/v1/dropsources.md
  content/en/docs/11.0/reference/vreplication/v1/movetables.md
  content/en/docs/11.0/reference/vreplication/v1/reshard.md
  content/en/docs/11.0/user-guides/configuration-advanced/integration-with-orchestrator.md
  content/en/docs/11.0/user-guides/configuration-advanced/reparenting.md
  content/en/docs/11.0/user-guides/migration/move-tables.md
  content/en/docs/11.0/user-guides/schema-changes/managed-online-schema-changes.md
  content/en/docs/11.0/user-guides/schema-changes/revertible-migrations.md
  content/en/docs/12.0/reference/programs/vtctl/_index.md
  content/en/docs/12.0/reference/programs/vtctl/keyspaces.md
  content/en/docs/12.0/reference/vreplication/v1/_index.md
  content/en/docs/12.0/reference/vreplication/v1/dropsources.md
  content/en/docs/12.0/reference/vreplication/v1/movetables.md
  content/en/docs/12.0/reference/vreplication/v1/reshard.md
  content/en/docs/12.0/user-guides/configuration-advanced/integration-with-orchestrator.md
  content/en/docs/13.0/reference/programs/vtctl/keyspaces.md
  content/en/docs/13.0/reference/vreplication/v1/_index.md
  content/en/docs/13.0/reference/vreplication/v1/dropsources.md
  content/en/docs/13.0/reference/vreplication/v1/movetables.md
  content/en/docs/13.0/reference/vreplication/v1/reshard.md
Labels: documentation

#942 last found broken links
  content/en/docs/11.0/concepts/vschema.md
  content/en/docs/11.0/reference/features/mysql-replication.md
  content/en/docs/11.0/user-guides/configuration-advanced/integration-with-orchestrator.md
  content/en/docs/12.0/reference/compatibility/mysql-compatibility.md
  content/en/docs/12.0/user-guides/configuration-advanced/integration-with-orchestrator.md
  content/en/docs/12.0/user-guides/configuration-advanced/reparenting.md
  content/en/docs/12.0/user-guides/schema-changes/managed-online-schema-changes.md
  content/en/docs/12.0/user-guides/schema-changes/revertible-migrations.md
Labels: documentation

#948 Document the usage of PlannedReparentShard with init_db.sql file
  content/en/docs/13.0/user-guides/configuration-basic/initialize-shard-primary.md
Labels: documentation

#952 Update the collations documentation following #9558
  content/en/docs/13.0/reference/programs/vtgate.md
  content/en/docs/13.0/reference/programs/vttablet.md
  content/en/docs/13.0/user-guides/configuration-basic/collations.md
Labels: documentation

#953 Add new ListAllTablets flags
  content/en/docs/13.0/reference/programs/vtctl/_index.md
  content/en/docs/13.0/reference/programs/vtctl/generic.md
Labels: documentation, do-not-merge
