Repository vitessio/website, pull requests merged in 2023-05, with the labels that each got.

#1458 Fix the resharding steps listed in the operator example
  content/en/docs/14.0/user-guides/configuration-advanced/resharding.md
  content/en/docs/15.0/user-guides/configuration-advanced/resharding.md
  content/en/docs/16.0/user-guides/configuration-advanced/resharding.md
  content/en/docs/17.0/user-guides/configuration-advanced/resharding.md
Labels: documentation

#1450 backup and restore blog
  content/en/blog/2023-05-08-backup-restore-compression.md
Labels: blog

#1454 Add documentation about grpc-use-static-authentication-callerid flag on vtgate
  content/en/docs/16.0/reference/features/transport-security-model.md
  content/en/docs/16.0/reference/programs/vtgate.md
  content/en/docs/17.0/reference/features/transport-security-model.md
  content/en/docs/17.0/reference/programs/vtgate.md
Labels: do-not-merge
